# fly.toml app configuration file generated for fs-psql-example on 2023-09-04T20:06:30+02:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "fs-psql-example"
primary_region = "ams"

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ["app"]
